language: node_js
node_js:
    - 8
before_script:
    - npm install @11ty/eleventy -g
script: eleventy --pathprefix="/"
deploy:
    local-dir: _site
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: 11ty
    target-branch: master # Default for this value is gh-pages, but user/organization pages are read from master so we have to add this field.

